#!/bin/sh
exited_cids=`docker ps -a | grep "Exit" | awk '{print $1}'`
if [ "x$exited_cids" != "x" ]; then
	docker rm $exited_cids
else
	echo "No exited containers to remove"
fi

none_img_ids=`docker images | grep "^<none>" | awk '{print $3}'`
if [ "x$none_img_ids" != "x" ]; then
	docker rmi none_img_ids
else
	echo "No garbage images to remove."
fi
